// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QueryParams { a: number, b: number, }
import callApi from './callApi';

export async function sum(params: QueryParams): Promise<number> {
    const response = await callApi("sum", params);
    return (await response.json()) as Promise<number>;
}

export async function sum_sub(params: QueryParams): Promise<number> {
    const response = await callApi("sum/sub", params);
    return (await response.json()) as Promise<number>;
}
